name: deeplearn
channels:
  - defaults
dependencies:
  - python=3.7
  - scipy
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - jupyterlab
  - spyder
  - h5py
  - opencv
  - scikit-learn
  - progressbar2
  - nodejs
  - cudatoolkit=10.0
  - cudnn
  - tensorflow-gpu=1.15.0
  - keras=2.2.4
  - pip:
    # - keras==2.2.4
    # - tensorflow-gpu==1.15.0
